apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pd-care-prod

resources:
  - namespace.yaml
  - ../../base
  - migrate-job.yaml
  - pdb.yaml

patches:
  - path: patch-configmap.yaml
  - path: patch-frontend.yaml
  - path: patch-backend.yaml
  - path: patch-ingress.yaml
  - path: patch-pvc-postgres.yaml
  - path: patch-pvc-seaweed-master.yaml
  - path: patch-pvc-seaweed-volume.yaml
  - path: patch-pvc-seaweed-filer.yaml

images:
  - name: pd-care-frontend
    newName: ghcr.io/ruby0322/pd-care-frontend
    newTag: prod-sha-9955444de793
  - name: pd-care-backend
    newName: ghcr.io/ruby0322/pd-care-backend
    newTag: sha-9955444de793
