apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pd-care
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - pd.lu.im.ntu.edu.tw
      secretName: pd-lu-im-ntu-edu-tw-tls
  rules:
    - host: pd.lu.im.ntu.edu.tw
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
