image:
  repository: ghcr.io/ruby0322/pd-care-backend
  tag: "prod-latest"

deployment:
  replicaCount: 3

hpa:
  minReplicas: 3
  maxReplicas: 12

pdb:
  minAvailable: 2

networkPolicy:
  enabled: true
  allowedNamespaces:
    - ingress-nginx
