apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pd-care-prod
  namespace: argocd
spec:
  project: pd-care
  source:
    repoURL: https://github.com/ruby0322/pd-care.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: pd-care-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
