image:
  repository: ghcr.io/ruby0322/pd-care-backend
  tag: "dev-latest"

deployment:
  replicaCount: 2

hpa:
  minReplicas: 2
  maxReplicas: 6

pdb:
  minAvailable: 1

networkPolicy:
  enabled: true
  allowedNamespaces:
    - ingress-nginx
