apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-filer
spec:
  selector:
    app: seaweedfs-filer
  ports:
    - name: filer
      port: 8888
      targetPort: 8888
    - name: filer-grpc
      port: 18888
      targetPort: 18888
