apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-master
spec:
  selector:
    app: seaweedfs-master
  ports:
    - name: master
      port: 9333
      targetPort: 9333
    - name: master-grpc
      port: 19333
      targetPort: 19333
