apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs-volume
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: seaweedfs-volume
  template:
    metadata:
      labels:
        app: seaweedfs-volume
    spec:
      containers:
        - name: seaweedfs-volume
          image: chrislusf/seaweedfs:3.76
          args:
            - volume
            - -mserver=seaweedfs-master:9333
            - -ip=seaweedfs-volume
            - -ip.bind=0.0.0.0
            - -dir=/data
            - -max=0
          ports:
            - containerPort: 8080
              name: volume-http
          volumeMounts:
            - name: seaweed-volume-data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
      volumes:
        - name: seaweed-volume-data
          persistentVolumeClaim:
            claimName: seaweed-volume-data
