apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pd-care-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patch-configmap.yaml
  - path: patch-frontend.yaml
  - path: patch-backend.yaml
  - path: patch-ingress.yaml
  - path: patch-pvc-postgres.yaml
  - path: patch-pvc-seaweed-master.yaml
  - path: patch-pvc-seaweed-volume.yaml
  - path: patch-pvc-seaweed-filer.yaml

images:
  - name: pd-care-frontend
    newName: ghcr.io/ruby0322/pd-care-frontend
    newTag: dev-sha-0a88adff5280
  - name: pd-care-backend
    newName: ghcr.io/ruby0322/pd-care-backend
    newTag: sha-8f548a5a0681
